include:
  - project: 'deploy/dev'
    file: '/go-app-v3.yml'
    ref: 'main'
  
lint dev:
  extends: .lint-dev
  
build dev:
  extends: .build-dev

deploy dev:
  extends: .deploy-dev
  script:
    # set environment
    - docker exec vault vault write auth/approle/role/app-${VAULT_APP} policies="app_${VAULT_APP}"
    - export AWS_ACCESS_KEY_ID=$(docker exec vault vault kv get -mount=secret -field=access_key_id app/media/awscredentials)
    - export AWS_SECRET_ACCESS_KEY=$(docker exec vault vault kv get -mount=secret -field=secret_access_key app/media/awscredentials)
    - export CONSUL_ADDRESS=http://consul:8500
    - export VAULT_ADDRESS=http://vault:8200
    - export VAULT_ROLE_ID=$(docker exec vault vault read -field=role_id auth/approle/role/app-${VAULT_APP}/role-id)
    - export VAULT_SECRET_ID=$(docker exec vault vault write -field=secret_id -f auth/approle/role/app-${VAULT_APP}/secret-id)
    - docker compose down
    # migrations up
    - docker pull arigaio/atlas
    - docker run --rm -v $(pwd)/ent/migrate/migrations:/migrations --network ${NETWORK} arigaio/atlas migrate apply --url "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_db:5432/${DB_NAME}?search_path=public&sslmode=disable"
    # service up
    - docker compose up -d
    - echo ${SERVICE_NAME} deployed successfully on dev

cleanup:
  extends: .cleanup

release:
  extends: .release

merge:
  extends: .merge

build-shell:
  extends: .build-shell

migration-build:
  extends: .migration-build

helm-lint:
  extends: .helm-lint

deploy:
  extends: .deploy

rollout:
  extends: .rollout
