// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"gitlab.calendaria.team/services/media/ent/media"
	"gitlab.calendaria.team/services/media/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	mediaMixin := schema.Media{}.Mixin()
	mediaMixinHooks0 := mediaMixin[0].Hooks()
	media.Hooks[0] = mediaMixinHooks0[0]
	mediaMixinInters0 := mediaMixin[0].Interceptors()
	media.Interceptors[0] = mediaMixinInters0[0]
	mediaFields := schema.Media{}.Fields()
	_ = mediaFields
	// mediaDescExtension is the schema descriptor for extension field.
	mediaDescExtension := mediaFields[2].Descriptor()
	// media.ExtensionValidator is a validator for the "extension" field. It is called by the builders before save.
	media.ExtensionValidator = func() func(string) error {
		validators := mediaDescExtension.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(extension string) error {
			for _, fn := range fns {
				if err := fn(extension); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// mediaDescIsActivated is the schema descriptor for is_activated field.
	mediaDescIsActivated := mediaFields[11].Descriptor()
	// media.DefaultIsActivated holds the default value on creation for the is_activated field.
	media.DefaultIsActivated = mediaDescIsActivated.Default.(bool)
	// mediaDescCreatedAt is the schema descriptor for created_at field.
	mediaDescCreatedAt := mediaFields[12].Descriptor()
	// media.DefaultCreatedAt holds the default value on creation for the created_at field.
	media.DefaultCreatedAt = mediaDescCreatedAt.Default.(func() time.Time)
	// mediaDescIsPrivate is the schema descriptor for is_private field.
	mediaDescIsPrivate := mediaFields[14].Descriptor()
	// media.DefaultIsPrivate holds the default value on creation for the is_private field.
	media.DefaultIsPrivate = mediaDescIsPrivate.Default.(bool)
}

const (
	Version = "v0.14.0"                                         // Version of ent codegen.
	Sum     = "h1:EO3Z9aZ5bXJatJeGqu/EVdnNr6K4mRq3rWe5owt0MC4=" // Sum of ent codegen.
)
