// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/media.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "github.com/makesalekz/media/ent"
	dto "github.com/makesalekz/media/internal/data/dto"
)

// MockMediaRepo is a mock of MediaRepo interface.
type MockMediaRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMediaRepoMockRecorder
}

// MockMediaRepoMockRecorder is the mock recorder for MockMediaRepo.
type MockMediaRepoMockRecorder struct {
	mock *MockMediaRepo
}

// NewMockMediaRepo creates a new mock instance.
func NewMockMediaRepo(ctrl *gomock.Controller) *MockMediaRepo {
	mock := &MockMediaRepo{ctrl: ctrl}
	mock.recorder = &MockMediaRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMediaRepo) EXPECT() *MockMediaRepoMockRecorder {
	return m.recorder
}

// CreateMedia mocks base method.
func (m *MockMediaRepo) CreateMedia(ctx context.Context, dto dto.CreateMediaDto) (*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMedia", ctx, dto)
	ret0, _ := ret[0].(*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMedia indicates an expected call of CreateMedia.
func (mr *MockMediaRepoMockRecorder) CreateMedia(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMedia", reflect.TypeOf((*MockMediaRepo)(nil).CreateMedia), ctx, dto)
}

// DeleteMedia mocks base method.
func (m *MockMediaRepo) DeleteMedia(ctx context.Context, mediaID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMedia", ctx, mediaID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMedia indicates an expected call of DeleteMedia.
func (mr *MockMediaRepoMockRecorder) DeleteMedia(ctx, mediaID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMedia", reflect.TypeOf((*MockMediaRepo)(nil).DeleteMedia), ctx, mediaID)
}

// DeleteMediaList mocks base method.
func (m *MockMediaRepo) DeleteMediaList(ctx context.Context, ids []int64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMediaList", ctx, ids)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMediaList indicates an expected call of DeleteMediaList.
func (mr *MockMediaRepoMockRecorder) DeleteMediaList(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMediaList", reflect.TypeOf((*MockMediaRepo)(nil).DeleteMediaList), ctx, ids)
}

// GetAvatarsMediaList mocks base method.
func (m *MockMediaRepo) GetAvatarsMediaList(ctx context.Context, urls []string) ([]*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarsMediaList", ctx, urls)
	ret0, _ := ret[0].([]*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvatarsMediaList indicates an expected call of GetAvatarsMediaList.
func (mr *MockMediaRepoMockRecorder) GetAvatarsMediaList(ctx, urls interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarsMediaList", reflect.TypeOf((*MockMediaRepo)(nil).GetAvatarsMediaList), ctx, urls)
}

// GetMedia mocks base method.
func (m *MockMediaRepo) GetMedia(ctx context.Context, mediaID int64) (*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMedia", ctx, mediaID)
	ret0, _ := ret[0].(*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMedia indicates an expected call of GetMedia.
func (mr *MockMediaRepoMockRecorder) GetMedia(ctx, mediaID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMedia", reflect.TypeOf((*MockMediaRepo)(nil).GetMedia), ctx, mediaID)
}

// GetMediaList mocks base method.
func (m *MockMediaRepo) GetMediaList(ctx context.Context, filter dto.FilterMediaDto) ([]*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMediaList", ctx, filter)
	ret0, _ := ret[0].([]*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMediaList indicates an expected call of GetMediaList.
func (mr *MockMediaRepoMockRecorder) GetMediaList(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMediaList", reflect.TypeOf((*MockMediaRepo)(nil).GetMediaList), ctx, filter)
}

// ListMedia mocks base method.
func (m *MockMediaRepo) ListMedia(ctx context.Context, mediaIDs []int64) ([]*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMedia", ctx, mediaIDs)
	ret0, _ := ret[0].([]*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMedia indicates an expected call of ListMedia.
func (mr *MockMediaRepoMockRecorder) ListMedia(ctx, mediaIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMedia", reflect.TypeOf((*MockMediaRepo)(nil).ListMedia), ctx, mediaIDs)
}

// SetDimensions mocks base method.
func (m *MockMediaRepo) SetDimensions(ctx context.Context, media *ent.Media, dto dto.SetDimensionsDto) (*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDimensions", ctx, media, dto)
	ret0, _ := ret[0].(*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDimensions indicates an expected call of SetDimensions.
func (mr *MockMediaRepoMockRecorder) SetDimensions(ctx, media, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDimensions", reflect.TypeOf((*MockMediaRepo)(nil).SetDimensions), ctx, media, dto)
}

// SetDuration mocks base method.
func (m *MockMediaRepo) SetDuration(ctx context.Context, media *ent.Media, duration float32) (*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDuration", ctx, media, duration)
	ret0, _ := ret[0].(*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetDuration indicates an expected call of SetDuration.
func (mr *MockMediaRepoMockRecorder) SetDuration(ctx, media, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDuration", reflect.TypeOf((*MockMediaRepo)(nil).SetDuration), ctx, media, duration)
}

// SetMediaLocation mocks base method.
func (m *MockMediaRepo) SetMediaLocation(ctx context.Context, media *ent.Media, location string) (*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMediaLocation", ctx, media, location)
	ret0, _ := ret[0].(*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetMediaLocation indicates an expected call of SetMediaLocation.
func (mr *MockMediaRepoMockRecorder) SetMediaLocation(ctx, media, location interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMediaLocation", reflect.TypeOf((*MockMediaRepo)(nil).SetMediaLocation), ctx, media, location)
}

// SetVideoParameters mocks base method.
func (m *MockMediaRepo) SetVideoParameters(ctx context.Context, video *ent.Media, dto dto.SetVideoParamsDto) (*ent.Media, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetVideoParameters", ctx, video, dto)
	ret0, _ := ret[0].(*ent.Media)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetVideoParameters indicates an expected call of SetVideoParameters.
func (mr *MockMediaRepoMockRecorder) SetVideoParameters(ctx, video, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVideoParameters", reflect.TypeOf((*MockMediaRepo)(nil).SetVideoParameters), ctx, video, dto)
}
