// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/s3.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockS3Uploader is a mock of S3Uploader interface.
type MockS3Uploader struct {
	ctrl     *gomock.Controller
	recorder *MockS3UploaderMockRecorder
}

// MockS3UploaderMockRecorder is the mock recorder for MockS3Uploader.
type MockS3UploaderMockRecorder struct {
	mock *MockS3Uploader
}

// NewMockS3Uploader creates a new mock instance.
func NewMockS3Uploader(ctrl *gomock.Controller) *MockS3Uploader {
	mock := &MockS3Uploader{ctrl: ctrl}
	mock.recorder = &MockS3UploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Uploader) EXPECT() *MockS3UploaderMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockS3Uploader) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockS3UploaderMockRecorder) Delete(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockS3Uploader)(nil).Delete), ctx, path)
}

// DeleteBulk mocks base method.
func (m *MockS3Uploader) DeleteBulk(ctx context.Context, paths []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBulk", ctx, paths)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBulk indicates an expected call of DeleteBulk.
func (mr *MockS3UploaderMockRecorder) DeleteBulk(ctx, paths interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBulk", reflect.TypeOf((*MockS3Uploader)(nil).DeleteBulk), ctx, paths)
}

// GetPresignedURL mocks base method.
func (m *MockS3Uploader) GetPreSignedURL(ctx context.Context, path string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreSignedURL", ctx, path)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPresignedURL indicates an expected call of GetPresignedURL.
func (mr *MockS3UploaderMockRecorder) GetPresignedURL(ctx, path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreSignedURL", reflect.TypeOf((*MockS3Uploader)(nil).GetPreSignedURL), ctx, path)
}

// Upload mocks base method.
func (m *MockS3Uploader) Upload(ctx context.Context, path string, fileData []byte, mimeType string, isPrivate bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, path, fileData, mimeType, isPrivate)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockS3UploaderMockRecorder) Upload(ctx, path, fileData, mimeType, isPrivate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockS3Uploader)(nil).Upload), ctx, path, fileData, mimeType, isPrivate)
}
