// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/makesalekz/media/internal/biz"
	"github.com/makesalekz/media/internal/conf"
	"github.com/makesalekz/media/internal/data"
	"github.com/makesalekz/media/internal/server"
	"github.com/makesalekz/media/internal/service"
	"github.com/makesalekz/utils/v1/config"
	"github.com/makesalekz/utils/v2/jwt"
	"github.com/makesalekz/utils/v2/nats"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	iJwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData)
	s3Uploader, err := data.NewS3Uploader(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	conn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	iQueueManager := nats.NewQueueManager(configConfig, conn, logger)
	mediaUsecase, err := biz.NewMediaUsecase(logger, mediaRepo, s3Uploader, iQueueManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mediaService := service.NewMediaService(mediaUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, iJwtProcessor, mediaService)
	httpServer := server.NewHTTPServer(bootstrap, iJwtProcessor)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
