// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/media/internal/biz"
	"gitlab.calendaria.team/services/media/internal/conf"
	"gitlab.calendaria.team/services/media/internal/data"
	"gitlab.calendaria.team/services/media/internal/server"
	"gitlab.calendaria.team/services/media/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v1/jwt"
	"gitlab.calendaria.team/services/utils/v1/nats"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData)
	s3Uploader, err := data.NewS3Uploader(configConfig)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	encodedConn, cleanup2, err := data.NewNatsClient(bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queueManager := nats.NewQueueManager(configConfig, encodedConn, logger)
	mediaUsecase, err := biz.NewMediaUsecase(logger, jwtProcessor, mediaRepo, s3Uploader, queueManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	mediaService := service.NewMediaService(mediaUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, jwtProcessor, mediaService)
	httpServer := server.NewHTTPServer(bootstrap, jwtProcessor)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
