// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "owner_id", Type: field.TypeInt64},
		{Name: "file_name", Type: field.TypeString},
		{Name: "extension", Type: field.TypeString, Size: 10},
		{Name: "path", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString, Nullable: true},
		{Name: "size", Type: field.TypeInt32},
		{Name: "width", Type: field.TypeInt32, Nullable: true},
		{Name: "height", Type: field.TypeInt32, Nullable: true},
		{Name: "duration", Type: field.TypeFloat32, Nullable: true},
		{Name: "is_activated", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "uploaded_at", Type: field.TypeTime, Nullable: true},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MediaTable,
	}
)

func init() {
}
