// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/media/ent/media"
	"github.com/makesalekz/media/ent/predicate"
)

// MediaUpdate is the builder for updating Media entities.
type MediaUpdate struct {
	config
	hooks    []Hook
	mutation *MediaMutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (mu *MediaUpdate) Where(ps ...predicate.Media) *MediaUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetDeletedAt sets the "deleted_at" field.
func (mu *MediaUpdate) SetDeletedAt(t time.Time) *MediaUpdate {
	mu.mutation.SetDeletedAt(t)
	return mu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableDeletedAt(t *time.Time) *MediaUpdate {
	if t != nil {
		mu.SetDeletedAt(*t)
	}
	return mu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (mu *MediaUpdate) ClearDeletedAt() *MediaUpdate {
	mu.mutation.ClearDeletedAt()
	return mu
}

// SetURL sets the "url" field.
func (mu *MediaUpdate) SetURL(s string) *MediaUpdate {
	mu.mutation.SetURL(s)
	return mu
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableURL(s *string) *MediaUpdate {
	if s != nil {
		mu.SetURL(*s)
	}
	return mu
}

// ClearURL clears the value of the "url" field.
func (mu *MediaUpdate) ClearURL() *MediaUpdate {
	mu.mutation.ClearURL()
	return mu
}

// SetSize sets the "size" field.
func (mu *MediaUpdate) SetSize(i int32) *MediaUpdate {
	mu.mutation.ResetSize()
	mu.mutation.SetSize(i)
	return mu
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableSize(i *int32) *MediaUpdate {
	if i != nil {
		mu.SetSize(*i)
	}
	return mu
}

// AddSize adds i to the "size" field.
func (mu *MediaUpdate) AddSize(i int32) *MediaUpdate {
	mu.mutation.AddSize(i)
	return mu
}

// SetWidth sets the "width" field.
func (mu *MediaUpdate) SetWidth(i int32) *MediaUpdate {
	mu.mutation.ResetWidth()
	mu.mutation.SetWidth(i)
	return mu
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableWidth(i *int32) *MediaUpdate {
	if i != nil {
		mu.SetWidth(*i)
	}
	return mu
}

// AddWidth adds i to the "width" field.
func (mu *MediaUpdate) AddWidth(i int32) *MediaUpdate {
	mu.mutation.AddWidth(i)
	return mu
}

// ClearWidth clears the value of the "width" field.
func (mu *MediaUpdate) ClearWidth() *MediaUpdate {
	mu.mutation.ClearWidth()
	return mu
}

// SetHeight sets the "height" field.
func (mu *MediaUpdate) SetHeight(i int32) *MediaUpdate {
	mu.mutation.ResetHeight()
	mu.mutation.SetHeight(i)
	return mu
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableHeight(i *int32) *MediaUpdate {
	if i != nil {
		mu.SetHeight(*i)
	}
	return mu
}

// AddHeight adds i to the "height" field.
func (mu *MediaUpdate) AddHeight(i int32) *MediaUpdate {
	mu.mutation.AddHeight(i)
	return mu
}

// ClearHeight clears the value of the "height" field.
func (mu *MediaUpdate) ClearHeight() *MediaUpdate {
	mu.mutation.ClearHeight()
	return mu
}

// SetDuration sets the "duration" field.
func (mu *MediaUpdate) SetDuration(f float32) *MediaUpdate {
	mu.mutation.ResetDuration()
	mu.mutation.SetDuration(f)
	return mu
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableDuration(f *float32) *MediaUpdate {
	if f != nil {
		mu.SetDuration(*f)
	}
	return mu
}

// AddDuration adds f to the "duration" field.
func (mu *MediaUpdate) AddDuration(f float32) *MediaUpdate {
	mu.mutation.AddDuration(f)
	return mu
}

// ClearDuration clears the value of the "duration" field.
func (mu *MediaUpdate) ClearDuration() *MediaUpdate {
	mu.mutation.ClearDuration()
	return mu
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (mu *MediaUpdate) SetThumbnailURL(s string) *MediaUpdate {
	mu.mutation.SetThumbnailURL(s)
	return mu
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableThumbnailURL(s *string) *MediaUpdate {
	if s != nil {
		mu.SetThumbnailURL(*s)
	}
	return mu
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (mu *MediaUpdate) ClearThumbnailURL() *MediaUpdate {
	mu.mutation.ClearThumbnailURL()
	return mu
}

// SetThumbnailPath sets the "thumbnail_path" field.
func (mu *MediaUpdate) SetThumbnailPath(s string) *MediaUpdate {
	mu.mutation.SetThumbnailPath(s)
	return mu
}

// SetNillableThumbnailPath sets the "thumbnail_path" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableThumbnailPath(s *string) *MediaUpdate {
	if s != nil {
		mu.SetThumbnailPath(*s)
	}
	return mu
}

// ClearThumbnailPath clears the value of the "thumbnail_path" field.
func (mu *MediaUpdate) ClearThumbnailPath() *MediaUpdate {
	mu.mutation.ClearThumbnailPath()
	return mu
}

// SetIsActivated sets the "is_activated" field.
func (mu *MediaUpdate) SetIsActivated(b bool) *MediaUpdate {
	mu.mutation.SetIsActivated(b)
	return mu
}

// SetNillableIsActivated sets the "is_activated" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableIsActivated(b *bool) *MediaUpdate {
	if b != nil {
		mu.SetIsActivated(*b)
	}
	return mu
}

// SetUploadedAt sets the "uploaded_at" field.
func (mu *MediaUpdate) SetUploadedAt(t time.Time) *MediaUpdate {
	mu.mutation.SetUploadedAt(t)
	return mu
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableUploadedAt(t *time.Time) *MediaUpdate {
	if t != nil {
		mu.SetUploadedAt(*t)
	}
	return mu
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (mu *MediaUpdate) ClearUploadedAt() *MediaUpdate {
	mu.mutation.ClearUploadedAt()
	return mu
}

// SetIsPrivate sets the "is_private" field.
func (mu *MediaUpdate) SetIsPrivate(b bool) *MediaUpdate {
	mu.mutation.SetIsPrivate(b)
	return mu
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableIsPrivate(b *bool) *MediaUpdate {
	if b != nil {
		mu.SetIsPrivate(*b)
	}
	return mu
}

// ClearIsPrivate clears the value of the "is_private" field.
func (mu *MediaUpdate) ClearIsPrivate() *MediaUpdate {
	mu.mutation.ClearIsPrivate()
	return mu
}

// Mutation returns the MediaMutation object of the builder.
func (mu *MediaUpdate) Mutation() *MediaMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MediaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MediaUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MediaUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MediaUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MediaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt64))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.DeletedAt(); ok {
		_spec.SetField(media.FieldDeletedAt, field.TypeTime, value)
	}
	if mu.mutation.DeletedAtCleared() {
		_spec.ClearField(media.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := mu.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if mu.mutation.URLCleared() {
		_spec.ClearField(media.FieldURL, field.TypeString)
	}
	if value, ok := mu.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeInt32, value)
	}
	if value, ok := mu.mutation.AddedSize(); ok {
		_spec.AddField(media.FieldSize, field.TypeInt32, value)
	}
	if value, ok := mu.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt32, value)
	}
	if value, ok := mu.mutation.AddedWidth(); ok {
		_spec.AddField(media.FieldWidth, field.TypeInt32, value)
	}
	if mu.mutation.WidthCleared() {
		_spec.ClearField(media.FieldWidth, field.TypeInt32)
	}
	if value, ok := mu.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt32, value)
	}
	if value, ok := mu.mutation.AddedHeight(); ok {
		_spec.AddField(media.FieldHeight, field.TypeInt32, value)
	}
	if mu.mutation.HeightCleared() {
		_spec.ClearField(media.FieldHeight, field.TypeInt32)
	}
	if value, ok := mu.mutation.Duration(); ok {
		_spec.SetField(media.FieldDuration, field.TypeFloat32, value)
	}
	if value, ok := mu.mutation.AddedDuration(); ok {
		_spec.AddField(media.FieldDuration, field.TypeFloat32, value)
	}
	if mu.mutation.DurationCleared() {
		_spec.ClearField(media.FieldDuration, field.TypeFloat32)
	}
	if value, ok := mu.mutation.ThumbnailURL(); ok {
		_spec.SetField(media.FieldThumbnailURL, field.TypeString, value)
	}
	if mu.mutation.ThumbnailURLCleared() {
		_spec.ClearField(media.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := mu.mutation.ThumbnailPath(); ok {
		_spec.SetField(media.FieldThumbnailPath, field.TypeString, value)
	}
	if mu.mutation.ThumbnailPathCleared() {
		_spec.ClearField(media.FieldThumbnailPath, field.TypeString)
	}
	if value, ok := mu.mutation.IsActivated(); ok {
		_spec.SetField(media.FieldIsActivated, field.TypeBool, value)
	}
	if value, ok := mu.mutation.UploadedAt(); ok {
		_spec.SetField(media.FieldUploadedAt, field.TypeTime, value)
	}
	if mu.mutation.UploadedAtCleared() {
		_spec.ClearField(media.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := mu.mutation.IsPrivate(); ok {
		_spec.SetField(media.FieldIsPrivate, field.TypeBool, value)
	}
	if mu.mutation.IsPrivateCleared() {
		_spec.ClearField(media.FieldIsPrivate, field.TypeBool)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MediaUpdateOne is the builder for updating a single Media entity.
type MediaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (muo *MediaUpdateOne) SetDeletedAt(t time.Time) *MediaUpdateOne {
	muo.mutation.SetDeletedAt(t)
	return muo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableDeletedAt(t *time.Time) *MediaUpdateOne {
	if t != nil {
		muo.SetDeletedAt(*t)
	}
	return muo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (muo *MediaUpdateOne) ClearDeletedAt() *MediaUpdateOne {
	muo.mutation.ClearDeletedAt()
	return muo
}

// SetURL sets the "url" field.
func (muo *MediaUpdateOne) SetURL(s string) *MediaUpdateOne {
	muo.mutation.SetURL(s)
	return muo
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableURL(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetURL(*s)
	}
	return muo
}

// ClearURL clears the value of the "url" field.
func (muo *MediaUpdateOne) ClearURL() *MediaUpdateOne {
	muo.mutation.ClearURL()
	return muo
}

// SetSize sets the "size" field.
func (muo *MediaUpdateOne) SetSize(i int32) *MediaUpdateOne {
	muo.mutation.ResetSize()
	muo.mutation.SetSize(i)
	return muo
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableSize(i *int32) *MediaUpdateOne {
	if i != nil {
		muo.SetSize(*i)
	}
	return muo
}

// AddSize adds i to the "size" field.
func (muo *MediaUpdateOne) AddSize(i int32) *MediaUpdateOne {
	muo.mutation.AddSize(i)
	return muo
}

// SetWidth sets the "width" field.
func (muo *MediaUpdateOne) SetWidth(i int32) *MediaUpdateOne {
	muo.mutation.ResetWidth()
	muo.mutation.SetWidth(i)
	return muo
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableWidth(i *int32) *MediaUpdateOne {
	if i != nil {
		muo.SetWidth(*i)
	}
	return muo
}

// AddWidth adds i to the "width" field.
func (muo *MediaUpdateOne) AddWidth(i int32) *MediaUpdateOne {
	muo.mutation.AddWidth(i)
	return muo
}

// ClearWidth clears the value of the "width" field.
func (muo *MediaUpdateOne) ClearWidth() *MediaUpdateOne {
	muo.mutation.ClearWidth()
	return muo
}

// SetHeight sets the "height" field.
func (muo *MediaUpdateOne) SetHeight(i int32) *MediaUpdateOne {
	muo.mutation.ResetHeight()
	muo.mutation.SetHeight(i)
	return muo
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableHeight(i *int32) *MediaUpdateOne {
	if i != nil {
		muo.SetHeight(*i)
	}
	return muo
}

// AddHeight adds i to the "height" field.
func (muo *MediaUpdateOne) AddHeight(i int32) *MediaUpdateOne {
	muo.mutation.AddHeight(i)
	return muo
}

// ClearHeight clears the value of the "height" field.
func (muo *MediaUpdateOne) ClearHeight() *MediaUpdateOne {
	muo.mutation.ClearHeight()
	return muo
}

// SetDuration sets the "duration" field.
func (muo *MediaUpdateOne) SetDuration(f float32) *MediaUpdateOne {
	muo.mutation.ResetDuration()
	muo.mutation.SetDuration(f)
	return muo
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableDuration(f *float32) *MediaUpdateOne {
	if f != nil {
		muo.SetDuration(*f)
	}
	return muo
}

// AddDuration adds f to the "duration" field.
func (muo *MediaUpdateOne) AddDuration(f float32) *MediaUpdateOne {
	muo.mutation.AddDuration(f)
	return muo
}

// ClearDuration clears the value of the "duration" field.
func (muo *MediaUpdateOne) ClearDuration() *MediaUpdateOne {
	muo.mutation.ClearDuration()
	return muo
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (muo *MediaUpdateOne) SetThumbnailURL(s string) *MediaUpdateOne {
	muo.mutation.SetThumbnailURL(s)
	return muo
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableThumbnailURL(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetThumbnailURL(*s)
	}
	return muo
}

// ClearThumbnailURL clears the value of the "thumbnail_url" field.
func (muo *MediaUpdateOne) ClearThumbnailURL() *MediaUpdateOne {
	muo.mutation.ClearThumbnailURL()
	return muo
}

// SetThumbnailPath sets the "thumbnail_path" field.
func (muo *MediaUpdateOne) SetThumbnailPath(s string) *MediaUpdateOne {
	muo.mutation.SetThumbnailPath(s)
	return muo
}

// SetNillableThumbnailPath sets the "thumbnail_path" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableThumbnailPath(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetThumbnailPath(*s)
	}
	return muo
}

// ClearThumbnailPath clears the value of the "thumbnail_path" field.
func (muo *MediaUpdateOne) ClearThumbnailPath() *MediaUpdateOne {
	muo.mutation.ClearThumbnailPath()
	return muo
}

// SetIsActivated sets the "is_activated" field.
func (muo *MediaUpdateOne) SetIsActivated(b bool) *MediaUpdateOne {
	muo.mutation.SetIsActivated(b)
	return muo
}

// SetNillableIsActivated sets the "is_activated" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableIsActivated(b *bool) *MediaUpdateOne {
	if b != nil {
		muo.SetIsActivated(*b)
	}
	return muo
}

// SetUploadedAt sets the "uploaded_at" field.
func (muo *MediaUpdateOne) SetUploadedAt(t time.Time) *MediaUpdateOne {
	muo.mutation.SetUploadedAt(t)
	return muo
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableUploadedAt(t *time.Time) *MediaUpdateOne {
	if t != nil {
		muo.SetUploadedAt(*t)
	}
	return muo
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (muo *MediaUpdateOne) ClearUploadedAt() *MediaUpdateOne {
	muo.mutation.ClearUploadedAt()
	return muo
}

// SetIsPrivate sets the "is_private" field.
func (muo *MediaUpdateOne) SetIsPrivate(b bool) *MediaUpdateOne {
	muo.mutation.SetIsPrivate(b)
	return muo
}

// SetNillableIsPrivate sets the "is_private" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableIsPrivate(b *bool) *MediaUpdateOne {
	if b != nil {
		muo.SetIsPrivate(*b)
	}
	return muo
}

// ClearIsPrivate clears the value of the "is_private" field.
func (muo *MediaUpdateOne) ClearIsPrivate() *MediaUpdateOne {
	muo.mutation.ClearIsPrivate()
	return muo
}

// Mutation returns the MediaMutation object of the builder.
func (muo *MediaUpdateOne) Mutation() *MediaMutation {
	return muo.mutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (muo *MediaUpdateOne) Where(ps ...predicate.Media) *MediaUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MediaUpdateOne) Select(field string, fields ...string) *MediaUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Media entity.
func (muo *MediaUpdateOne) Save(ctx context.Context) (*Media, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MediaUpdateOne) SaveX(ctx context.Context) *Media {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MediaUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MediaUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MediaUpdateOne) sqlSave(ctx context.Context) (_node *Media, err error) {
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt64))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Media.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, media.FieldID)
		for _, f := range fields {
			if !media.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != media.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.DeletedAt(); ok {
		_spec.SetField(media.FieldDeletedAt, field.TypeTime, value)
	}
	if muo.mutation.DeletedAtCleared() {
		_spec.ClearField(media.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := muo.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
	}
	if muo.mutation.URLCleared() {
		_spec.ClearField(media.FieldURL, field.TypeString)
	}
	if value, ok := muo.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeInt32, value)
	}
	if value, ok := muo.mutation.AddedSize(); ok {
		_spec.AddField(media.FieldSize, field.TypeInt32, value)
	}
	if value, ok := muo.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt32, value)
	}
	if value, ok := muo.mutation.AddedWidth(); ok {
		_spec.AddField(media.FieldWidth, field.TypeInt32, value)
	}
	if muo.mutation.WidthCleared() {
		_spec.ClearField(media.FieldWidth, field.TypeInt32)
	}
	if value, ok := muo.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt32, value)
	}
	if value, ok := muo.mutation.AddedHeight(); ok {
		_spec.AddField(media.FieldHeight, field.TypeInt32, value)
	}
	if muo.mutation.HeightCleared() {
		_spec.ClearField(media.FieldHeight, field.TypeInt32)
	}
	if value, ok := muo.mutation.Duration(); ok {
		_spec.SetField(media.FieldDuration, field.TypeFloat32, value)
	}
	if value, ok := muo.mutation.AddedDuration(); ok {
		_spec.AddField(media.FieldDuration, field.TypeFloat32, value)
	}
	if muo.mutation.DurationCleared() {
		_spec.ClearField(media.FieldDuration, field.TypeFloat32)
	}
	if value, ok := muo.mutation.ThumbnailURL(); ok {
		_spec.SetField(media.FieldThumbnailURL, field.TypeString, value)
	}
	if muo.mutation.ThumbnailURLCleared() {
		_spec.ClearField(media.FieldThumbnailURL, field.TypeString)
	}
	if value, ok := muo.mutation.ThumbnailPath(); ok {
		_spec.SetField(media.FieldThumbnailPath, field.TypeString, value)
	}
	if muo.mutation.ThumbnailPathCleared() {
		_spec.ClearField(media.FieldThumbnailPath, field.TypeString)
	}
	if value, ok := muo.mutation.IsActivated(); ok {
		_spec.SetField(media.FieldIsActivated, field.TypeBool, value)
	}
	if value, ok := muo.mutation.UploadedAt(); ok {
		_spec.SetField(media.FieldUploadedAt, field.TypeTime, value)
	}
	if muo.mutation.UploadedAtCleared() {
		_spec.ClearField(media.FieldUploadedAt, field.TypeTime)
	}
	if value, ok := muo.mutation.IsPrivate(); ok {
		_spec.SetField(media.FieldIsPrivate, field.TypeBool, value)
	}
	if muo.mutation.IsPrivateCleared() {
		_spec.ClearField(media.FieldIsPrivate, field.TypeBool)
	}
	_node = &Media{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
