// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/media/ent/media"
)

// MediaCreate is the builder for creating a Media entity.
type MediaCreate struct {
	config
	mutation *MediaMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (mc *MediaCreate) SetDeletedAt(t time.Time) *MediaCreate {
	mc.mutation.SetDeletedAt(t)
	return mc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mc *MediaCreate) SetNillableDeletedAt(t *time.Time) *MediaCreate {
	if t != nil {
		mc.SetDeletedAt(*t)
	}
	return mc
}

// SetOwnerID sets the "owner_id" field.
func (mc *MediaCreate) SetOwnerID(i int64) *MediaCreate {
	mc.mutation.SetOwnerID(i)
	return mc
}

// SetFileName sets the "file_name" field.
func (mc *MediaCreate) SetFileName(s string) *MediaCreate {
	mc.mutation.SetFileName(s)
	return mc
}

// SetExtension sets the "extension" field.
func (mc *MediaCreate) SetExtension(s string) *MediaCreate {
	mc.mutation.SetExtension(s)
	return mc
}

// SetPath sets the "path" field.
func (mc *MediaCreate) SetPath(s string) *MediaCreate {
	mc.mutation.SetPath(s)
	return mc
}

// SetURL sets the "url" field.
func (mc *MediaCreate) SetURL(s string) *MediaCreate {
	mc.mutation.SetURL(s)
	return mc
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (mc *MediaCreate) SetNillableURL(s *string) *MediaCreate {
	if s != nil {
		mc.SetURL(*s)
	}
	return mc
}

// SetSize sets the "size" field.
func (mc *MediaCreate) SetSize(i int32) *MediaCreate {
	mc.mutation.SetSize(i)
	return mc
}

// SetWidth sets the "width" field.
func (mc *MediaCreate) SetWidth(i int32) *MediaCreate {
	mc.mutation.SetWidth(i)
	return mc
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (mc *MediaCreate) SetNillableWidth(i *int32) *MediaCreate {
	if i != nil {
		mc.SetWidth(*i)
	}
	return mc
}

// SetHeight sets the "height" field.
func (mc *MediaCreate) SetHeight(i int32) *MediaCreate {
	mc.mutation.SetHeight(i)
	return mc
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (mc *MediaCreate) SetNillableHeight(i *int32) *MediaCreate {
	if i != nil {
		mc.SetHeight(*i)
	}
	return mc
}

// SetDuration sets the "duration" field.
func (mc *MediaCreate) SetDuration(f float32) *MediaCreate {
	mc.mutation.SetDuration(f)
	return mc
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (mc *MediaCreate) SetNillableDuration(f *float32) *MediaCreate {
	if f != nil {
		mc.SetDuration(*f)
	}
	return mc
}

// SetThumbnailURL sets the "thumbnail_url" field.
func (mc *MediaCreate) SetThumbnailURL(s string) *MediaCreate {
	mc.mutation.SetThumbnailURL(s)
	return mc
}

// SetNillableThumbnailURL sets the "thumbnail_url" field if the given value is not nil.
func (mc *MediaCreate) SetNillableThumbnailURL(s *string) *MediaCreate {
	if s != nil {
		mc.SetThumbnailURL(*s)
	}
	return mc
}

// SetThumbnailPath sets the "thumbnail_path" field.
func (mc *MediaCreate) SetThumbnailPath(s string) *MediaCreate {
	mc.mutation.SetThumbnailPath(s)
	return mc
}

// SetNillableThumbnailPath sets the "thumbnail_path" field if the given value is not nil.
func (mc *MediaCreate) SetNillableThumbnailPath(s *string) *MediaCreate {
	if s != nil {
		mc.SetThumbnailPath(*s)
	}
	return mc
}

// SetIsActivated sets the "is_activated" field.
func (mc *MediaCreate) SetIsActivated(b bool) *MediaCreate {
	mc.mutation.SetIsActivated(b)
	return mc
}

// SetNillableIsActivated sets the "is_activated" field if the given value is not nil.
func (mc *MediaCreate) SetNillableIsActivated(b *bool) *MediaCreate {
	if b != nil {
		mc.SetIsActivated(*b)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MediaCreate) SetCreatedAt(t time.Time) *MediaCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MediaCreate) SetNillableCreatedAt(t *time.Time) *MediaCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetUploadedAt sets the "uploaded_at" field.
func (mc *MediaCreate) SetUploadedAt(t time.Time) *MediaCreate {
	mc.mutation.SetUploadedAt(t)
	return mc
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (mc *MediaCreate) SetNillableUploadedAt(t *time.Time) *MediaCreate {
	if t != nil {
		mc.SetUploadedAt(*t)
	}
	return mc
}

// Mutation returns the MediaMutation object of the builder.
func (mc *MediaCreate) Mutation() *MediaMutation {
	return mc.mutation
}

// Save creates the Media in the database.
func (mc *MediaCreate) Save(ctx context.Context) (*Media, error) {
	if err := mc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MediaCreate) SaveX(ctx context.Context) *Media {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MediaCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MediaCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MediaCreate) defaults() error {
	if _, ok := mc.mutation.IsActivated(); !ok {
		v := media.DefaultIsActivated
		mc.mutation.SetIsActivated(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		if media.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized media.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := media.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (mc *MediaCreate) check() error {
	if _, ok := mc.mutation.OwnerID(); !ok {
		return &ValidationError{Name: "owner_id", err: errors.New(`ent: missing required field "Media.owner_id"`)}
	}
	if _, ok := mc.mutation.FileName(); !ok {
		return &ValidationError{Name: "file_name", err: errors.New(`ent: missing required field "Media.file_name"`)}
	}
	if _, ok := mc.mutation.Extension(); !ok {
		return &ValidationError{Name: "extension", err: errors.New(`ent: missing required field "Media.extension"`)}
	}
	if v, ok := mc.mutation.Extension(); ok {
		if err := media.ExtensionValidator(v); err != nil {
			return &ValidationError{Name: "extension", err: fmt.Errorf(`ent: validator failed for field "Media.extension": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Media.path"`)}
	}
	if _, ok := mc.mutation.Size(); !ok {
		return &ValidationError{Name: "size", err: errors.New(`ent: missing required field "Media.size"`)}
	}
	if _, ok := mc.mutation.IsActivated(); !ok {
		return &ValidationError{Name: "is_activated", err: errors.New(`ent: missing required field "Media.is_activated"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Media.created_at"`)}
	}
	return nil
}

func (mc *MediaCreate) sqlSave(ctx context.Context) (*Media, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MediaCreate) createSpec() (*Media, *sqlgraph.CreateSpec) {
	var (
		_node = &Media{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(media.Table, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt64))
	)
	if value, ok := mc.mutation.DeletedAt(); ok {
		_spec.SetField(media.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := mc.mutation.OwnerID(); ok {
		_spec.SetField(media.FieldOwnerID, field.TypeInt64, value)
		_node.OwnerID = value
	}
	if value, ok := mc.mutation.FileName(); ok {
		_spec.SetField(media.FieldFileName, field.TypeString, value)
		_node.FileName = value
	}
	if value, ok := mc.mutation.Extension(); ok {
		_spec.SetField(media.FieldExtension, field.TypeString, value)
		_node.Extension = value
	}
	if value, ok := mc.mutation.Path(); ok {
		_spec.SetField(media.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := mc.mutation.URL(); ok {
		_spec.SetField(media.FieldURL, field.TypeString, value)
		_node.URL = &value
	}
	if value, ok := mc.mutation.Size(); ok {
		_spec.SetField(media.FieldSize, field.TypeInt32, value)
		_node.Size = value
	}
	if value, ok := mc.mutation.Width(); ok {
		_spec.SetField(media.FieldWidth, field.TypeInt32, value)
		_node.Width = &value
	}
	if value, ok := mc.mutation.Height(); ok {
		_spec.SetField(media.FieldHeight, field.TypeInt32, value)
		_node.Height = &value
	}
	if value, ok := mc.mutation.Duration(); ok {
		_spec.SetField(media.FieldDuration, field.TypeFloat32, value)
		_node.Duration = &value
	}
	if value, ok := mc.mutation.ThumbnailURL(); ok {
		_spec.SetField(media.FieldThumbnailURL, field.TypeString, value)
		_node.ThumbnailURL = &value
	}
	if value, ok := mc.mutation.ThumbnailPath(); ok {
		_spec.SetField(media.FieldThumbnailPath, field.TypeString, value)
		_node.ThumbnailPath = &value
	}
	if value, ok := mc.mutation.IsActivated(); ok {
		_spec.SetField(media.FieldIsActivated, field.TypeBool, value)
		_node.IsActivated = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(media.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UploadedAt(); ok {
		_spec.SetField(media.FieldUploadedAt, field.TypeTime, value)
		_node.UploadedAt = &value
	}
	return _node, _spec
}

// MediaCreateBulk is the builder for creating many Media entities in bulk.
type MediaCreateBulk struct {
	config
	builders []*MediaCreate
}

// Save creates the Media entities in the database.
func (mcb *MediaCreateBulk) Save(ctx context.Context) ([]*Media, error) {
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Media, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MediaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MediaCreateBulk) SaveX(ctx context.Context) []*Media {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MediaCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MediaCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
