// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"media/internal/biz"
	"media/internal/conf"
	"media/internal/data"
	"media/internal/server"
	"media/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	config, err := data.NewConfig(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := data.NewJwtProcessor(config)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	mediaRepo := data.NewMediaRepo(dataData)
	s3Uploader, err := data.NewS3Uploader(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	natsClient, cleanup2, err := data.NewNatsClient(config)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	queueManager := biz.NewQueueManager(config, natsClient, logger)
	mediaUsecase, err := biz.NewMediaUsecase(logger, config, jwtProcessor, mediaRepo, s3Uploader, queueManager)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	uploadService := service.NewUploadService(logger, jwtProcessor, mediaUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, uploadService)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, uploadService)
	app := newApp(logger, config, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
