// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.0
// - protoc             v4.23.4
// source: media/v1/media.proto

package media_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMediaServiceUploadMedia = "/api.media.v1.MediaService/UploadMedia"

type MediaServiceHTTPServer interface {
	UploadMedia(context.Context, *UploadMediaRequest) (*MediaReply, error)
}

func RegisterMediaServiceHTTPServer(s *http.Server, srv MediaServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/media", _MediaService_UploadMedia0_HTTP_Handler(srv))
}

func _MediaService_UploadMedia0_HTTP_Handler(srv MediaServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UploadMediaRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMediaServiceUploadMedia)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UploadMedia(ctx, req.(*UploadMediaRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*MediaReply)
		return ctx.Result(200, reply)
	}
}

type MediaServiceHTTPClient interface {
	UploadMedia(ctx context.Context, req *UploadMediaRequest, opts ...http.CallOption) (rsp *MediaReply, err error)
}

type MediaServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewMediaServiceHTTPClient(client *http.Client) MediaServiceHTTPClient {
	return &MediaServiceHTTPClientImpl{client}
}

func (c *MediaServiceHTTPClientImpl) UploadMedia(ctx context.Context, in *UploadMediaRequest, opts ...http.CallOption) (*MediaReply, error) {
	var out MediaReply
	pattern := "/v1/media"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMediaServiceUploadMedia))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
