// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/media/v1/media.proto

package media_v1

import (
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	httpbody "google.golang.org/genproto/googleapis/api/httpbody"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       *httpbody.HttpBody     `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=fileName,proto3" json:"fileName,omitempty"`    // header: X-File-Name
	FilePath      string                 `protobuf:"bytes,4,opt,name=filePath,proto3" json:"filePath,omitempty"`    // header: X-File-Path
	IsPrivate     bool                   `protobuf:"varint,5,opt,name=isPrivate,proto3" json:"isPrivate,omitempty"` // header: X-File-Private
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMediaRequest) Reset() {
	*x = UploadMediaRequest{}
	mi := &file_api_media_v1_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMediaRequest) ProtoMessage() {}

func (x *UploadMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMediaRequest.ProtoReflect.Descriptor instead.
func (*UploadMediaRequest) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadMediaRequest) GetContent() *httpbody.HttpBody {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadMediaRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadMediaRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *UploadMediaRequest) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

type MediaReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaReply) Reset() {
	*x = MediaReply{}
	mi := &file_api_media_v1_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaReply) ProtoMessage() {}

func (x *MediaReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaReply.ProtoReflect.Descriptor instead.
func (*MediaReply) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaReply) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type GetMediaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int64                  `protobuf:"varint,1,opt,name=mediaId,proto3" json:"mediaId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaRequest) Reset() {
	*x = GetMediaRequest{}
	mi := &file_api_media_v1_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaRequest) ProtoMessage() {}

func (x *GetMediaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaRequest.ProtoReflect.Descriptor instead.
func (*GetMediaRequest) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{2}
}

func (x *GetMediaRequest) GetMediaId() int64 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type GetMediaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaIds      []int64                `protobuf:"varint,2,rep,packed,name=mediaIds,proto3" json:"mediaIds,omitempty"`
	OwnOnly       bool                   `protobuf:"varint,3,opt,name=ownOnly,proto3" json:"ownOnly,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMediaListRequest) Reset() {
	*x = GetMediaListRequest{}
	mi := &file_api_media_v1_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMediaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMediaListRequest) ProtoMessage() {}

func (x *GetMediaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMediaListRequest.ProtoReflect.Descriptor instead.
func (*GetMediaListRequest) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{3}
}

func (x *GetMediaListRequest) GetMediaIds() []int64 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *GetMediaListRequest) GetOwnOnly() bool {
	if x != nil {
		return x.OwnOnly
	}
	return false
}

type MediaListReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         []*Media               `protobuf:"bytes,1,rep,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListReply) Reset() {
	*x = MediaListReply{}
	mi := &file_api_media_v1_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListReply) ProtoMessage() {}

func (x *MediaListReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListReply.ProtoReflect.Descriptor instead.
func (*MediaListReply) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{4}
}

func (x *MediaListReply) GetMedia() []*Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type DeleteAvatarRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []string               `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAvatarRequest) Reset() {
	*x = DeleteAvatarRequest{}
	mi := &file_api_media_v1_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAvatarRequest) ProtoMessage() {}

func (x *DeleteAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAvatarRequest.ProtoReflect.Descriptor instead.
func (*DeleteAvatarRequest) Descriptor() ([]byte, []int) {
	return file_api_media_v1_media_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteAvatarRequest) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

var File_api_media_v1_media_proto protoreflect.FileDescriptor

const file_api_media_v1_media_proto_rawDesc = "" +
	"\n" +
	"\x18api/media/v1/media.proto\x12\bmedia.v1\x1a\x19google/api/httpbody.proto\x1a\x19api/utils/v1/models.proto\x1a\x19api/media/v1/models.proto\"\x9a\x01\n" +
	"\x12UploadMediaRequest\x12.\n" +
	"\acontent\x18\x02 \x01(\v2\x14.google.api.HttpBodyR\acontent\x12\x1a\n" +
	"\bfileName\x18\x03 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfilePath\x18\x04 \x01(\tR\bfilePath\x12\x1c\n" +
	"\tisPrivate\x18\x05 \x01(\bR\tisPrivate\"3\n" +
	"\n" +
	"MediaReply\x12%\n" +
	"\x05media\x18\x01 \x01(\v2\x0f.media.v1.MediaR\x05media\"+\n" +
	"\x0fGetMediaRequest\x12\x18\n" +
	"\amediaId\x18\x01 \x01(\x03R\amediaId\"K\n" +
	"\x13GetMediaListRequest\x12\x1a\n" +
	"\bmediaIds\x18\x02 \x03(\x03R\bmediaIds\x12\x18\n" +
	"\aownOnly\x18\x03 \x01(\bR\aownOnly\"7\n" +
	"\x0eMediaListReply\x12%\n" +
	"\x05media\x18\x01 \x03(\v2\x0f.media.v1.MediaR\x05media\")\n" +
	"\x13DeleteAvatarRequest\x12\x12\n" +
	"\x04urls\x18\x01 \x03(\tR\x04urls2\xe0\x02\n" +
	"\fMediaService\x12A\n" +
	"\vUploadMedia\x12\x1c.media.v1.UploadMediaRequest\x1a\x14.media.v1.MediaReply\x12B\n" +
	"\x0fGetPrivateMedia\x12\x19.media.v1.GetMediaRequest\x1a\x14.media.v1.MediaReply\x12;\n" +
	"\bGetMedia\x12\x19.media.v1.GetMediaRequest\x1a\x14.media.v1.MediaReply\x12G\n" +
	"\fGetMediaList\x12\x1d.media.v1.GetMediaListRequest\x1a\x18.media.v1.MediaListReply\x12C\n" +
	"\fDeleteAvatar\x12\x1d.media.v1.DeleteAvatarRequest\x1a\x14.utils.v1.EmptyReplyBI\n" +
	"\bmedia.v1P\x01Z;gitlab.calendaria.team/services/media/api/media/v1;media_v1b\x06proto3"

var (
	file_api_media_v1_media_proto_rawDescOnce sync.Once
	file_api_media_v1_media_proto_rawDescData []byte
)

func file_api_media_v1_media_proto_rawDescGZIP() []byte {
	file_api_media_v1_media_proto_rawDescOnce.Do(func() {
		file_api_media_v1_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_media_v1_media_proto_rawDesc), len(file_api_media_v1_media_proto_rawDesc)))
	})
	return file_api_media_v1_media_proto_rawDescData
}

var file_api_media_v1_media_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_media_v1_media_proto_goTypes = []any{
	(*UploadMediaRequest)(nil),  // 0: media.v1.UploadMediaRequest
	(*MediaReply)(nil),          // 1: media.v1.MediaReply
	(*GetMediaRequest)(nil),     // 2: media.v1.GetMediaRequest
	(*GetMediaListRequest)(nil), // 3: media.v1.GetMediaListRequest
	(*MediaListReply)(nil),      // 4: media.v1.MediaListReply
	(*DeleteAvatarRequest)(nil), // 5: media.v1.DeleteAvatarRequest
	(*httpbody.HttpBody)(nil),   // 6: google.api.HttpBody
	(*Media)(nil),               // 7: media.v1.Media
	(*v1.EmptyReply)(nil),       // 8: utils.v1.EmptyReply
}
var file_api_media_v1_media_proto_depIdxs = []int32{
	6, // 0: media.v1.UploadMediaRequest.content:type_name -> google.api.HttpBody
	7, // 1: media.v1.MediaReply.media:type_name -> media.v1.Media
	7, // 2: media.v1.MediaListReply.media:type_name -> media.v1.Media
	0, // 3: media.v1.MediaService.UploadMedia:input_type -> media.v1.UploadMediaRequest
	2, // 4: media.v1.MediaService.GetPrivateMedia:input_type -> media.v1.GetMediaRequest
	2, // 5: media.v1.MediaService.GetMedia:input_type -> media.v1.GetMediaRequest
	3, // 6: media.v1.MediaService.GetMediaList:input_type -> media.v1.GetMediaListRequest
	5, // 7: media.v1.MediaService.DeleteAvatar:input_type -> media.v1.DeleteAvatarRequest
	1, // 8: media.v1.MediaService.UploadMedia:output_type -> media.v1.MediaReply
	1, // 9: media.v1.MediaService.GetPrivateMedia:output_type -> media.v1.MediaReply
	1, // 10: media.v1.MediaService.GetMedia:output_type -> media.v1.MediaReply
	4, // 11: media.v1.MediaService.GetMediaList:output_type -> media.v1.MediaListReply
	8, // 12: media.v1.MediaService.DeleteAvatar:output_type -> utils.v1.EmptyReply
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_media_v1_media_proto_init() }
func file_api_media_v1_media_proto_init() {
	if File_api_media_v1_media_proto != nil {
		return
	}
	file_api_media_v1_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_media_v1_media_proto_rawDesc), len(file_api_media_v1_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_media_v1_media_proto_goTypes,
		DependencyIndexes: file_api_media_v1_media_proto_depIdxs,
		MessageInfos:      file_api_media_v1_media_proto_msgTypes,
	}.Build()
	File_api_media_v1_media_proto = out.File
	file_api_media_v1_media_proto_goTypes = nil
	file_api_media_v1_media_proto_depIdxs = nil
}
