// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/media/v1/models.proto

package media_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId       int64                  `protobuf:"varint,2,opt,name=ownerId,proto3" json:"ownerId,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	FileName      string                 `protobuf:"bytes,4,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Extension     string                 `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	Size          int32                  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`                 // in bytes
	Width         *int32                 `protobuf:"varint,8,opt,name=width,proto3,oneof" json:"width,omitempty"`         // in pixels
	Height        *int32                 `protobuf:"varint,9,opt,name=height,proto3,oneof" json:"height,omitempty"`       // in pixels
	Duration      *float32               `protobuf:"fixed32,10,opt,name=duration,proto3,oneof" json:"duration,omitempty"` // in seconds
	ThumbnailUrl  *string                `protobuf:"bytes,11,opt,name=thumbnailUrl,proto3,oneof" json:"thumbnailUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_api_media_v1_models_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_api_media_v1_models_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_api_media_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Media) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *Media) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *Media) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Media) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Media) GetWidth() int32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *Media) GetHeight() int32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *Media) GetDuration() float32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

func (x *Media) GetThumbnailUrl() string {
	if x != nil && x.ThumbnailUrl != nil {
		return *x.ThumbnailUrl
	}
	return ""
}

var File_api_media_v1_models_proto protoreflect.FileDescriptor

const file_api_media_v1_models_proto_rawDesc = "" +
	"\n" +
	"\x19api/media/v1/models.proto\x12\bmedia.v1\"\xe4\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x18\n" +
	"\aownerId\x18\x02 \x01(\x03R\aownerId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1a\n" +
	"\bfileName\x18\x04 \x01(\tR\bfileName\x12\x1c\n" +
	"\textension\x18\x05 \x01(\tR\textension\x12\x1c\n" +
	"\tcreatedAt\x18\x06 \x01(\tR\tcreatedAt\x12\x12\n" +
	"\x04size\x18\a \x01(\x05R\x04size\x12\x19\n" +
	"\x05width\x18\b \x01(\x05H\x00R\x05width\x88\x01\x01\x12\x1b\n" +
	"\x06height\x18\t \x01(\x05H\x01R\x06height\x88\x01\x01\x12\x1f\n" +
	"\bduration\x18\n" +
	" \x01(\x02H\x02R\bduration\x88\x01\x01\x12'\n" +
	"\fthumbnailUrl\x18\v \x01(\tH\x03R\fthumbnailUrl\x88\x01\x01B\b\n" +
	"\x06_widthB\t\n" +
	"\a_heightB\v\n" +
	"\t_durationB\x0f\n" +
	"\r_thumbnailUrlBI\n" +
	"\bmedia.v1P\x01Z;gitlab.calendaria.team/services/media/api/media/v1;media_v1b\x06proto3"

var (
	file_api_media_v1_models_proto_rawDescOnce sync.Once
	file_api_media_v1_models_proto_rawDescData []byte
)

func file_api_media_v1_models_proto_rawDescGZIP() []byte {
	file_api_media_v1_models_proto_rawDescOnce.Do(func() {
		file_api_media_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_media_v1_models_proto_rawDesc), len(file_api_media_v1_models_proto_rawDesc)))
	})
	return file_api_media_v1_models_proto_rawDescData
}

var file_api_media_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_media_v1_models_proto_goTypes = []any{
	(*Media)(nil), // 0: media.v1.Media
}
var file_api_media_v1_models_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_media_v1_models_proto_init() }
func file_api_media_v1_models_proto_init() {
	if File_api_media_v1_models_proto != nil {
		return
	}
	file_api_media_v1_models_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_media_v1_models_proto_rawDesc), len(file_api_media_v1_models_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_media_v1_models_proto_goTypes,
		DependencyIndexes: file_api_media_v1_models_proto_depIdxs,
		MessageInfos:      file_api_media_v1_models_proto_msgTypes,
	}.Build()
	File_api_media_v1_models_proto = out.File
	file_api_media_v1_models_proto_goTypes = nil
	file_api_media_v1_models_proto_depIdxs = nil
}
