image:
  # image config
  repository: 
  tag: 
  pullPolicy: IfNotPresent
  imagePullSecrets:

fullnameOverride: media
nameOverride: media
namespaceOverride: stage-backend
configmap:
  private:
    enabled: false
  data:
    DEBUG: "1"
    SERVICE_NAME: "media"
    AUTOMIGRATE: "true"
    CONSUL_ADDRESS: "http://10.2.5.6:8500"
    VAULT_ADDRESS: "http://10.2.4.5:8200"
    VAULT_ROLE_ID: "a32a7739-0e4b-f68b-e61e-5832feac3257"
    VAULT_SECRET_ID: "66fd885b-8ed1-90ed-8253-4f739914ea1e"


server:
  replicaCount: 1
  command: ["./media", "-conf", "./config.yaml"]
  podSecurityContext: {}
  securityContext: {}
  serviceAccount:

  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 0.5
      memory: 0.5Gi

  service:
    type: ClusterIP
    port: 80
    targetPort: 8000
    
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 512m
      nginx.ingress.kubernetes.io/rewrite-target: /$1
    path: /media/?(.*)
    hosts:
      - stage.calendaria.net
    tls:
    - secretName: calendaria-tls
      hosts:
        - stage.calendaria.net

  nodeSelector: {}
  tolerations: []
  affinity: {}

