-- Create "media" table
CREATE TABLE "media" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "owner_id" bigint NOT NULL, "file_name" character varying NOT NULL, "extension" character varying NOT NULL, "path" character varying NOT NULL, "url" character varying NULL, "size" integer NOT NULL, "width" integer NULL, "height" integer NULL, "duration" integer NULL, "created_at" timestamptz NOT NULL, "uploaded_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "media_path_key" to table: "media"
CREATE UNIQUE INDEX "media_path_key" ON "media" ("path");
